spring:
    docker:
        compose:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    profiles:
        active: '@spring.profiles.active@'
