spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: backend
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tech_challenge}
        username: backend
    docker:
        compose:
            enabled: true
            file: compose-dev.yaml
            # Recreates db_dev container so sql scripts (mapped volumes in compose) are executed each time
            start:
                command: up
            stop:
                command: down
