spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: backend
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tech_challenge}
        username: backend
    devtools:
        add-properties: false
