# Global config
spring:
    docker:
        compose:
            # We don't want to use docker compose in prod and test
            enabled: false
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    profiles:
        # Value comes from Maven profile (pom.xml)
        active: '@spring.profiles.active@'
springdoc:
    swagger-ui:
        path: /
        tags-sorter: alpha
