# This compose file is for development only!
# In "production" (compose in dev root) the
# spring docker compose integration will be deactivated
# and will try to connect to the DB directly.
# This is because the backend will already be inside a container.
services:
  db_dev:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tech_challenge'
      - 'POSTGRES_PASSWORD=backend'
      - 'POSTGRES_USER=backend'
    volumes:
      - ./db/01-create-tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
      - ./db/02-insert-fixed-data.sql:/docker-entrypoint-initdb.d/02-insert-fixed-data.sql
      - ./db/03-insert-example-data.sql:/docker-entrypoint-initdb.d/03-insert-example-data.sql
    ports:
      - 5432:5432
