apiVersion: v1
kind: Service
metadata:
  name: soat-tech-challenge-db-service
  namespace: fiap-grupo-63
spec:
  selector:
      app: soat-tech-challenge-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: soat-tech-challenge-backend-service
  namespace: fiap-grupo-63
spec:
  type: NodePort
  selector:
    app: soat-tech-challenge-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000