apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-tech-challenge-backend-deployment
  namespace: fiap-grupo-63
  annotations:
    ignore-check.kube-linter.io/latest-tag: "This deployment is for the application whose tags are managed in the same repository."
    ignore-check.kube-linter.io/no-read-only-root-fs: "Tomcat and other Spring Boot tools may write to filesystem (e.g /tmp)."
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soat-tech-challenge-backend
  template:
    metadata:
      labels:
        app: soat-tech-challenge-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: g0tn/soat-tech-challenge-backend:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "soat-tech-challenge-db-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: soat-tech-challenge-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soat-tech-challenge-db-secret
                  key: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-tech-challenge-db-deployment
  namespace: fiap-grupo-63
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Postgres needs write access to its container file system."
    ignore-check.kube-linter.io/run-as-non-root: "Postgres needs elevated permissions within its container."
spec:
  selector:
    matchLabels:
      app: soat-tech-challenge-db
  template:
    metadata:
      labels:
        app: soat-tech-challenge-db
    spec:
      containers:
        - name: db
          image: postgres:15.4
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "1"
          volumeMounts:
            - name: soat-tech-challenge-db-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tech_challenge"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: soat-tech-challenge-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: soat-tech-challenge-db-secret
                  key: password
      volumes:
        - name: soat-tech-challenge-db-scripts-volume
          configMap:
            name: soat-tech-challenge-db-scripts-configmap
