name: Build

on:
  push:
    branches: main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build, bump and push
    runs-on: ubuntu-latest
    environment:
      name: Docker Hub
      url: https://hub.docker.com/layers/${{ vars.DOCKER_IMAGE_NAME }}/${{ steps.bump.outputs.tag }}/images/${{ steps.docker_build_push.outputs.digest }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUMP_PAT }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - name: Run Tests
        run: mvn test -B -P prod "-Dstyle.color=always"

      - name: Bump Maven version
        id: bump
        uses: soat-tech-challenge/gh-action-bump-maven-version@main
        with:
          commit-message: '[skip ci] Bump version to'

      - name: Package with Maven
        run: mvn package -B -P prod "-Dmaven.test.skip" "-Dstyle.color=always"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: docker_build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.bump.outputs.tag }},${{ vars.DOCKER_IMAGE_NAME }}:latest
